version: 2.1
executors:
  exectr_cmake:
    docker:
      - image: $GITHUB_CMAKE_IMAGE
        auth:
          username: $GITHUB_USERNAME
          password: $GITHUB_TOKEN
    resource_class: small

jobs:
  build:
    executor: exectr_cmake
    steps:
      - checkout
      - run:
          name: Build CMAKE
          command: cmake -Bbuild .
      - run:
          name: Build CXX
          command: cmake --build ./build
      - persist_to_workspace:
          root: .
          paths: 
            - build
  test:
    executor: exectr_cmake
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/tst
            ./GameOfLife_tst --gtest_output=xml
      - store_test_results:
          path: build
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
              - build