# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  cmake: sensu/cmake@1.0.0
# Orchestrate or schedule a set of jobs
workflows:
  build:
    docker:
      - image: ghcr.io/jonathanabrahams/alpine-cmake:1.0.0
        auth:
          username: jonathanabrahams
          password: $GITHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Build CMAKE
          command: cmake -Bbuild .
      - run:
          name: List all
          command: ls -la ./build
      - run:
          name: Build CXX
          command: cmake --build ./build
      - run:
          name: List SRC
          command: ls -la ./build/src
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run