version: 2.1
jobs:
  build:
    docker:
      - image: ghcr.io/jonathanabrahams/alpine-cmake:1.0.0
        auth:
          username: jonathanabrahams
          password: $GITHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Build CMAKE
          command: cmake -Bbuild .
      - run:
          name: List all
          command: ls -la ./build
      - run:
          name: Build CXX
          command: cmake --build ./build
      - run:
          name: List SRC
          command: ls -la ./build/src
workflows:
  build:
    jobs:
      - build